### ISSUE TITLE
Write instructions for setting up the dev environment

### ISSUE THREAD

**Issue by ZhiqinLuUCI** [Geometry-Discovery-Project/homepage#85]
# How to install pnpm to view webpage created in your own branch (Mac)

# Open terminal in Mac

# Install brew 

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/zhiqinlu/.zprofile

eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'export PATH="/usr/local/opt/node@16/bin:$PATH"' >> ~/.zshrc

# git to your branch

# Download and install node.js

# I don't know how npm had been installed, but then

sudo 4pm I -g pnpm

pnpm i
pnpm run fix

pnpm build

pnpm serve

# Hold the command key and click the local server

http://localhost:8080/ 

should work.

**Comment by Kiyo5hi** [comment]
I will move this to `README.md` and close this issue.

**Comment by Kiyo5hi** [comment]
DONE
