### ISSUE TITLE
GDP Icon

### ISSUE THREAD

**Issue by ZhiqinLuUCI** [Geometry-Discovery-Project/homepage#86]
# The GDP Icon Issue

## Here is the snapshot of the banner of the gdp webpage

<img width="378" alt="Screen Shot 2022-06-18 at 9 14 20 AM" src="https://user-images.githubusercontent.com/97719898/174447663-b7adef2f-1553-4066-be40-0cd1d1c48625.png">

The GDP icon file is fine, but with the black background, the letter "G" and "P" are partially cut.

## Possible solutions:

1. Change the black background to a lighter one, or
2. Modify the color of the text GDP in the GDP icon file so that it shows over the black background.

**Comment by Kiyo5hi** [comment]
[e2fd280b811ccf16d64e7e4e9ac269d65f1327bd](https://github.com/Geometry-Discovery-Project-UCI/homepage/commit/e2fd280b811ccf16d64e7e4e9ac269d65f1327bd)
